---
apiVersion: v1
kind: Service
metadata:
  name: deny-env
  namespace: deny-env
spec:
  type: ClusterIP
  selector:
    app: deny-env
  ports:
  - name: port-1
    port: 443
    protocol: TCP
    targetPort: 8083
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deny-env
  namespace: deny-env
  labels:
    app: deny-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deny-env
  template:
    metadata:
      labels:
        app: deny-env
    spec:
      containers:
      - name: deny-env-var-validator
        image:  pandorasnox/kubernetes-deny-env-var:1.0.0
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: tls-certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: tls-cert-deny-env-var-validator
